version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: defiut
      MYSQL_USER: admin
      MYSQL_PASSWORD: defiut23
    ports:
      - "3305:3306"
    volumes:
      - ./data/mysql/.:/var/lib/mysql

  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_app-container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./node_modules/.:/app/node_modules
