version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: defiut
      MYSQL_USER: admin
      MYSQL_PASSWORD: defiut23
      MYSQL_ROOT_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - "3305:3306"
    volumes:
      - ./data/mysql/.:/var/lib/mysql
    command: >
      --authentication_policy=mysql_native_password
    networks:
      - numeria-network

  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_app-container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./node_modules/.:/app/node_modules
    networks:
      - numeria-network
    environment:
    - NODE_VERSION=16
    - DOCKER_ENV=true

networks:
  numeria-network:
    driver: bridge