version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: defiut
      MYSQL_USER: admin
      MYSQL_PASSWORD: defiut23
      MYSQL_ROOT_AUTHENTICATION_PLUGIN: mysql_native_password
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
      MYSQL_TCP_PORT: 3306
    ports:
      - "3305:3306"
    command: 
      ["mysqld", "--mysql-native-password=ON"]
    volumes:
      - ./data/mysql/.:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - numeria-network

  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_app-container
    ports:
      - "3000:3000"
    networks:
      - numeria-network
    environment:
      - NODE_VERSION=16
      - DOCKER_ENV=true
      - MYSQL_HOST=mysql
    depends_on:
      - mysql



networks:
  numeria-network:
    driver: bridge